// ========== Default Configuration ==========

export const WALRUS_CONFIG = {
  CHUNK_THRESHOLD_BYTES: 50 * 1024 * 1024, // 50 MB
  CHUNK_SIZE_BYTES: 10 * 1024 * 1024, // 10 MB
  MAX_CONCURRENT_CHUNKS: 3,
  DEFAULT_EPOCHS: 5,
  RETRY_MAX_ATTEMPTS: 3,
  RETRY_BASE_MS: 1000,
  RETRY_MAX_MS: 30_000,
  RETRY_FACTOR: 2,
} as const;

export const AUTH_CONFIG = {
  CHALLENGE_TTL_SECONDS: 300,
  ACCESS_TOKEN_TTL_SECONDS: 900, // 15 min
  REFRESH_TOKEN_TTL_SECONDS: 604800, // 7 days
  MAX_SESSIONS_PER_USER: 5,
} as const;

export const RATE_LIMIT_CONFIG = {
  DEFAULT_WINDOW_MS: 60_000, // 1 minute
  DEFAULT_MAX_REQUESTS: 60,
  AUTH_MAX_REQUESTS: 10,
  UPLOAD_MAX_REQUESTS: 20,
} as const;

export const PAGINATION_CONFIG = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
